version: "3.3"

services:
  bun-ngx-upstream:
    build:
      context: .
      dockerfile: ./config/bun.dockerfile
    command: >
      sh -c "bun ./packages/backend/src/index.ts --bootstrap=8081,8082,8083,8084,8085"
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    restart: always
    volumes:
      - "./:/app"
    environment:
      CC_APP_NAME: "bun-ngx-upstream-ws"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
