version: '3.8'

services:
  openresty:
    image: openresty/openresty:1.21.4.1-jammy
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
